<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Bootstrap-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>

    <!--Favicon-->
    <link rel="shortcut icon" href="../assets/favicon.ico" type="image/x-icon">
    
    <!--Font Awesome-->
    <script src="https://kit.fontawesome.com/391c4a19d2.js" crossorigin="anonymous"></script>

    <!--Ajax-->
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>

    <!--Boxicons CSS-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <link rel="stylesheet" href="../css/index.css">

    <title>Gerencia v2 - Index</title>
    
</head>
<body>
    
    <nav class="sidebar close">
        <header>
            <div class="image-text">
                <span class="image">
                    <img src="../assets/logo.svg" alt="logo">
                </span>

                <div class="text header-text">
                    <span class="nome">GERENCIA</span>
                    <span class="versao">V2</span>
                </div>
            </div>

            <i class='bx bx-chevron-right toggle'></i>
        </header>

        <div class="menu-bar">
            <div class="menu">
                <li class="search-box">
                    <i class='bx bx-search icon'></i>
                        <input type="text" placeholder="Procurar...">
                </li>
                <ul class="menu-links">
                    <li class="nav-link">
                        <a href="index.phtml">
                            <i class='bx bx-pie-chart-alt icon' ></i>
                            <span class="text nav-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="protocolo.phtml">
                            <i class='bx bx-note icon' ></i>
                            <span class="text nav-text">Protocolo</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="servico.phtml">
                            <i class='bx bxs-package icon' ></i>
                            <span class="text nav-text">Serviço</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="agenda.phtml">
                            <i class='bx bx-calendar icon' ></i>
                            <span class="text nav-text">Agenda</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="config.phtml">
                            <i class='bx bx-cog icon' ></i>
                            <span class="text nav-text">Configurações</span>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="bottom-content">
                <li class="">
                    <a href="#">
                        <i class='bx bx-log-out icon' ></i>
                        <span class="text nav-text">Sair</span>
                    </a>
                </li>
                
                <li class="mode">
                    <div class="moon-sun">
                        <i class='bx bx-moon icon moon' ></i>
                        <i class='bx bx-sun icon sun' ></i>
                    </div>
                    <span class="mode-text text">Dark Mode</span>

                    <div class="toggle-switch">
                        <span class="switch"></span>
                    </div>

                </li>
            </div>
        </div>
    </nav>

    <section class="home">
        <div class="text">Darshboard</div>
    </section>
    
    <div>
        <p class="text2">TEXTO</p>
    </div>
    
    <script src="../js/index.js"></script>

</body>
</html>