<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="../assets/favicon.ico" type="image/x-icon">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js" integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="../login.css">

    <title>Gerencia v2 - Login</title>

</head>
<body>
    <section>
        <div class="form-box">
            <div class="form-value">
                <form action="">
                    <h2>Login</h2>
                    <div class="inputbox">
                        <ion-icon name="mail-outline"></ion-icon>
                        <input type="email" required>
                        <label for="">Email</label>
                    </div>
                    <div class="inputbox">
                        <ion-icon name="lock-closed-outline"></ion-icon>
                        <input type="password" required>
                        <label for="">Senha</label>
                    </div>
                    <div class="esqueci">
                        <label for=""><span><input type="checkbox">Lembrar senha</span> <a href="#">Esqueci minha senha</a></label>
                    </div>
                    <button>Entrar</button>
                </form>
            </div>
        </div>
    </section>
    <!--Aqui ele altera o fundo automaticamente sem que a imagem se repita-->
    <script> 
        function randFundo(){
        var fundo = [1,2][Math.floor(Math.random()*2)];
        !localStorage.fundo ? localStorage.fundo = fundo : 0;
        return localStorage.fundo == fundo
        ?
        (localStorage.fundo = fundo+1)
        :
        (localStorage.fundo = fundo);
        }

        var e_header = document.querySelector("section");
        e_header.style.backgroundImage = "url(../assets/background"+randFundo()+".jpg)";
    </script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>